# Generated by Django 5.1 on 2026-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, help_text='6-digit code for password recovery.', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiration time for the reset code.', null=True),
        ),
    ]
