# Generated by Django 5.1 on 2026-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_reset_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Base64 encoded profile image string.', null=True),
        ),
    ]
