# Generated by Django 5.1 on 2026-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('locked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted Email',
                'verbose_name_plural': 'Blacklisted Emails',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, citizen cannot submit SOS and responder cannot toggle on duty.'),
        ),
    ]
