# Generated by Django 5.1 on 2026-04-17 09:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='GPS coordinates of the emergency (longitude, latitude).', srid=4326)),
                ('address', models.CharField(blank=True, default='', help_text='Human-readable address of the emergency location.', max_length=500)),
                ('category', models.CharField(choices=[('MEDICAL', 'Medical Emergency'), ('FIRE', 'Fire'), ('CRIME', 'Crime'), ('ACCIDENT', 'Road Accident'), ('NATURAL_DISASTER', 'Natural Disaster'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved')], db_index=True, default='PENDING', max_length=15)),
                ('title', models.CharField(help_text='Short summary of the incident.', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the emergency.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_responder', models.ForeignKey(blank=True, help_text='The responder currently handling this incident.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(help_text='The citizen who reported this incident.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved')], help_text='The new status after this transition.', max_length=15)),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved')], default='', help_text='The status before this transition.', max_length=15)),
                ('note', models.TextField(blank=True, default='', help_text='Optional note explaining the status change.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('incident', models.ForeignKey(help_text='The incident this log entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='incidents.incident')),
                ('responder', models.ForeignKey(help_text='The responder who triggered this status change.', on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Response Log',
                'verbose_name_plural': 'Response Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='incidents_i_status_85e429_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category', 'status'], name='incidents_i_categor_2b6a8a_idx'),
        ),
    ]
