# Generated by Django 5.1 on 2026-05-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='', help_text='The status before this transition.', max_length=15),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], help_text='The new status after this transition.', max_length=15),
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(help_text='Base64 encoded string of the uploaded image.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Evidence',
                'verbose_name_plural': 'Incident Evidences',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
