# Generated by Django 5.1 on 2026-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='', help_text='The status before this transition.', max_length=15),
        ),
        migrations.AlterField(
            model_name='responselog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], help_text='The new status after this transition.', max_length=15),
        ),
    ]
